forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum
main_media:
    resource: "@MainBundle/Controller/MediaController.php"
    type:     annotation
event_event:
    resource: "@MainBundle/Controller/EventController.php"
    type:     annotation

event_events:
    resource: "@MainBundle/Controller/EventsController.php"
    type:     annotation
main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /main

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

