event_index:
    path:     /
    defaults: { _controller: "MainBundle:Event:index" }
    methods:  GET

event_show:
    path:     /{idEv}/show
    defaults: { _controller: "MainBundle:Event:show" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "MainBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{idEv}/edit
    defaults: { _controller: "MainBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{idEv}/delete
    defaults: { _controller: "MainBundle:Event:delete" }
    methods:  DELETE

event_part:
    path:     /part
    defaults: { _controller: "MainBundle:Event:part" }
    methods:  GET
