main_events:
    resource: "@MainBundle/Resources/config/routing/events.yml"
    prefix:   /event
main_event:
    resource: "@MainBundle/Resources/config/routing/event.yml"
    prefix:   /events

admin_page:
    path:     /admin
    defaults: { _controller: "MainBundle:Events:baseback" }

organisateur_page:
    path:     /org
    defaults: { _controller: "MainBundle:Events:organisateur" }


