main_events:
    resource: "@MainBundle/Resources/config/routing/events.yml"
    prefix:   /event
main_event:
    resource: "@MainBundle/Resources/config/routing/event.yml"
    prefix:   /events
main_media:
    resource: "@MainBundle/Resources/config/routing/media.yml"
    prefix:   /media

admin_page:
    path:     /admin
    defaults: { _controller: "MainBundle:Events:baseback" }

organisateur_page:
    path:     /org
    defaults: { _controller: "MainBundle:Event:organisateur" }
participant_page:
    path:     /part
    defaults: { _controller: "MainBundle:Event:participant" }



